runner-default: powershell # shell, in which commands will be executed

presets:
  default:
    command: cargo run
    run:
      after: # commands, that will be executed after the project is built
        - mv /target/debug/project_name.exe ~/compiled # moves the compiled executable to HOME/compiled folder
        - echo "moved!"