# hello there!

runner-default: current

presets:
  macro:
    runner: powershell
    command: clear

  default:
    command:
      - clear
      - ls
    run:
      before:
        - clear
      after: macro