# runny build

#runner-default: bash

#presets:
#  build:
#    command: cargo r
#    run:
#      after: echo "builded!"
#
#  default:
#    command: clear
#    run:
#      after: build

runner-default: powershell

presets:
  after:
    command: echo "after"

  default:
    command: echo "default command"
    run:
      before:
        - echo "before"
      after: after